wordConfig:
  luckyWord: Irish  
---
spring:
  profiles: subject
words: I,You,He,She
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
