eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
spring: 
  profiles: lab-4-subject
words: I,You,He,She

---
spring: 
  profiles: lab-4-verb
words: ran,knew,had,saw,bought
